# Generated by Django 4.1 on 2024-05-01 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guest', '0001_initial'),
        ('hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('appid', models.AutoField(primary_key=True, serialize=False)),
                ('reqdate', models.DateField(auto_now_add=True, null=True)),
                ('appdate', models.DateField(null=True)),
                ('apptime', models.TimeField(null=True)),
                ('status', models.CharField(max_length=50)),
                ('remark', models.CharField(max_length=300, null=True)),
                ('docid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.doctor')),
                ('hosserid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.hosservice')),
                ('patid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='guest.patient')),
            ],
        ),
        migrations.CreateModel(
            name='patienthistory',
            fields=[
                ('caseid', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
                ('symptoms', models.CharField(max_length=50)),
                ('prescription', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('appid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patientapp.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('feedid', models.AutoField(primary_key=True, serialize=False)),
                ('feeddetails', models.CharField(max_length=50)),
                ('hosid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='guest.hospital')),
                ('patid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='guest.patient')),
            ],
        ),
    ]
