# Generated by Django 4.1 on 2024-05-01 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guest', '0001_initial'),
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hosservice',
            fields=[
                ('hosserid', models.AutoField(primary_key=True, serialize=False)),
                ('hospitalid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='guest.hospital')),
                ('serid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adminapp.service')),
            ],
        ),
        migrations.CreateModel(
            name='hospitaldepartment',
            fields=[
                ('hosdepid', models.AutoField(primary_key=True, serialize=False)),
                ('depid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adminapp.department')),
                ('hosid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='guest.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('docid', models.AutoField(primary_key=True, serialize=False)),
                ('docname', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('qualification', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=50)),
                ('regdate', models.DateField(auto_now_add=True)),
                ('OnlineTime', models.TimeField()),
                ('depid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adminapp.department')),
                ('hosid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='guest.hospital')),
                ('locid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adminapp.location')),
                ('loginid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='guest.tbllogin')),
            ],
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('compid', models.AutoField(primary_key=True, serialize=False)),
                ('compdetails', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('hosid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='guest.hospital')),
                ('patid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='guest.patient')),
            ],
        ),
    ]
