# Generated by Django 4.1 on 2024-05-01 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('depid', models.AutoField(primary_key=True, serialize=False)),
                ('depname', models.CharField(max_length=50)),
                ('depphoto', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='district',
            fields=[
                ('disid', models.AutoField(primary_key=True, serialize=False)),
                ('disname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('serid', models.AutoField(primary_key=True, serialize=False)),
                ('sername', models.CharField(max_length=50)),
                ('serTime', models.IntegerField(null=True)),
                ('serphoto', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('locid', models.AutoField(primary_key=True, serialize=False)),
                ('locname', models.CharField(max_length=50)),
                ('disid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adminapp.district')),
            ],
        ),
    ]
